[Settings]
ID = "cybno"

[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# REDIRECTS
# - Note that all redirects will match on first hit, so be very careful

# Redirect for our bylaws
[[redirects]]
  from = "https://vedtekter.cyb.no/*"
  to = "https://cybernetisk.github.io/docs/vedtekter/vedtekter.pdf"
  status = 200
  force = true

# Redirect okonomi paths
[[redirects]]
  from = "/okonomi/*"
  to = "https://cybernetisk.github.io/okotools/:splat"
  status = 200

# Redirect all paths that don't match to our storage at the
# webserver maintained by the Department of Informatics
[[redirects]]
  from = "/*"
  to = "http://cyb.ifi.uio.no/:splat"
  status = 200
